"""Base trading strategy interface."""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from datetime import datetime
import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    action: str  # 'buy', 'sell', 'hold'
    symbol: str
    price: float
    amount: float
    confidence: float  # 0.0 to 1.0
    timestamp: datetime
    metadata: Dict[str, Any] = None


@dataclass
class Position:
    """Current position information."""
    symbol: str
    side: str  # 'long', 'short'
    amount: float
    entry_price: float
    current_price: float
    pnl: float
    timestamp: datetime


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.name = self.__class__.__name__
        self.positions: Dict[str, Position] = {}
        self.historical_data: Dict[str, pd.DataFrame] = {}
    
    @abstractmethod
    async def analyze(self, symbol: str, timeframe: str = "1h") -> Signal:
        """Analyze market data and generate trading signal."""
        pass
    
    @abstractmethod
    async def should_exit(self, position: Position, current_price: float) -> bool:
        """Determine if current position should be closed."""
        pass
    
    @abstractmethod
    def get_position_size(self, symbol: str, price: float, balance: float) -> float:
        """Calculate position size based on risk management."""
        pass
    
    def update_historical_data(self, symbol: str, data: pd.DataFrame):
        """Update historical price data for analysis."""
        self.historical_data[symbol] = data
    
    def add_position(self, position: Position):
        """Add a new position to tracking."""
        self.positions[position.symbol] = position
    
    def remove_position(self, symbol: str):
        """Remove position from tracking."""
        if symbol in self.positions:
            del self.positions[symbol]
    
    def update_position_price(self, symbol: str, current_price: float):
        """Update current price for position."""
        if symbol in self.positions:
            position = self.positions[symbol]
            position.current_price = current_price
            
            # Calculate P&L
            if position.side == 'long':
                position.pnl = (current_price - position.entry_price) * position.amount
            else:  # short
                position.pnl = (position.entry_price - current_price) * position.amount
    
    def get_risk_parameters(self) -> Dict[str, float]:
        """Get risk management parameters."""
        return {
            'max_position_size': self.config.get('max_position_size', 1000),
            'risk_per_trade': self.config.get('risk_per_trade', 0.02),  # 2%
            'stop_loss': self.config.get('stop_loss', 0.05),  # 5%
            'take_profit': self.config.get('take_profit', 0.10),  # 10%
        }
    
    def calculate_stop_loss(self, entry_price: float, side: str) -> float:
        """Calculate stop loss price."""
        risk_params = self.get_risk_parameters()
        stop_loss_pct = risk_params['stop_loss']
        
        if side == 'long':
            return entry_price * (1 - stop_loss_pct)
        else:  # short
            return entry_price * (1 + stop_loss_pct)
    
    def calculate_take_profit(self, entry_price: float, side: str) -> float:
        """Calculate take profit price."""
        risk_params = self.get_risk_parameters()
        take_profit_pct = risk_params['take_profit']
        
        if side == 'long':
            return entry_price * (1 + take_profit_pct)
        else:  # short
            return entry_price * (1 - take_profit_pct)